GET http://localhost:3000/ 
###
POST http://localhost:3000/adduser
Content-Type: application/json 

{
 "username":"ArunKumar",
 "email":"arunnandu333@gmail.com",
 "password":"Arun@7328",
 "phonenumber":9964983218
}

### 
DELETE http://localhost:3000/delete/63aae4477974bbb4d494a2da


